import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useTranslations } from 'use-intl';
import styles from '../styles/Home.module.css';
import PetsIcon from '@mui/icons-material/Pets';
import LanguageSelector from '../components/languageSelector';
import { Avatar, IconButton } from '@mui/material';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import { useRouter } from 'next/dist/client/router';

const Home: NextPage = () => {
	const t = useTranslations('index');
	const router = useRouter();

	return (
		<div className={styles.container}>
			<Head>
				<title>DigDog</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					{t('welcomeTo')} DigD<a>o</a>g<PetsIcon></PetsIcon>
				</h1>
				<div className={styles.languageSettings}>
					<LanguageSelector></LanguageSelector>
					<IconButton
						onClick={() => {
							router.push('/main', '/main');
						}}
						aria-label='select language and continue'
						size='large'
					>
						<ArrowForwardIcon></ArrowForwardIcon>
					</IconButton>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
				<a
					href='https://github.com/kumibrr/dig-dog-next'
					target='_blank'
					rel='noopener noreferrer'
				>
					Created by{' '}
					<span className='avatar'>
						<Avatar
							style={{ marginLeft: '7px' }}
							alt='kumibrr github avatar'
							src='https://avatars.githubusercontent.com/u/13884133?v=4'
						/>
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;

export function getStaticProps({ locale }: { locale: string }) {
	return {
		props: {
			messages: {
				...require(`../public/i18n/${locale}.json`),
			},
		},
	};
}
