import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useTranslations } from "use-intl";
import styles from "../styles/Home.module.css";
import PetsIcon from "@mui/icons-material/Pets";

const Home: NextPage = () => {
  const t = useTranslations("index");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t("welcomeTo")}{" "}
          <a>
            Dig D<a>o</a>g
          </a>
          <PetsIcon></PetsIcon>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      messages: {
        ...require(`../public/i18n/${locale}.json`),
      },
    },
  };
}
